test___thread:
	g++ -o test___thread test___thread.cpp -lpthread

test_pthread_once:
	g++ -o test_pthread_once test_pthread_once.cpp -lpthread

test_tls:
	g++ -g -o test_tls test_tls.cpp -lpthread

clean:
	rm -f test___thread test_tls test_pthread_once
